DROP TABLE "EX";
DROP TABLE "EX_CASHCARD";
DROP TABLE "EX_CATEGORY";
DROP TABLE "EX_MEMBER";
DROP SEQUENCE SEQ_EX;

CREATE SEQUENCE SEQ_EX;

CREATE TABLE "EX" (
	"INSERT_DATE"	DATE		NOT NULL,
	"NO"	        NUMBER		NOT NULL,
	"MID"	        VARCHAR2(20)		NOT NULL,
	"PRICE"	        NUMBER		NOT NULL,
	"CATEGORY"	    VARCHAR(20)		NOT NULL,
	"CASHCARD"	    VARCHAR(20)		NOT NULL,
	"NAME"	        VARCHAR2(50)		NOT NULL,
	"DESCRIPTION"	VARCHAR(50)		NULL
);
CREATE TABLE "EX_CASHCARD" (
	"CASHCARD"	VARCHAR(20)		NOT NULL
);
CREATE TABLE "EX_CATEGORY" (
	"CATEGORY"	VARCHAR(20)		NOT NULL
);
CREATE TABLE "EX_MEMBER" (
	"MID"	VARCHAR2(20)		NOT NULL,
	"MPWD"	VARCHAR2(20)		NOT NULL,
	"MNAME"	VARCHAR2(20)		NOT NULL,
	"MEMAIL"	VARCHAR2(50)		NOT NULL
);
ALTER TABLE "EX" ADD CONSTRAINT "PK_EX" PRIMARY KEY (
	"INSERT_DATE", "NO"
);
ALTER TABLE "EX_CASHCARD" ADD CONSTRAINT "PK_EX_CASHCARD" PRIMARY KEY (
	"CASHCARD"
);
ALTER TABLE "EX_CATEGORY" ADD CONSTRAINT "PK_EX_CATEGORY" PRIMARY KEY (
	"CATEGORY"
);
ALTER TABLE "EX_MEMBER" ADD CONSTRAINT "PK_EX_MEMBER" PRIMARY KEY (
	"MID"
);
ALTER TABLE "EX" ADD CONSTRAINT "FK_EX_MEMBER_TO_EX_1" FOREIGN KEY (
	"MID"
)
REFERENCES "EX_MEMBER" (
	"MID"
);
ALTER TABLE "EX" ADD CONSTRAINT "FK_EX_CATEGORY_TO_EX_1" FOREIGN KEY (
	"CATEGORY"
)
REFERENCES "EX_CATEGORY" (
	"CATEGORY"
);
ALTER TABLE "EX" ADD CONSTRAINT "FK_EX_CASHCARD_TO_EX_1" FOREIGN KEY (
	"CASHCARD"
)
REFERENCES "EX_CASHCARD" (
	"CASHCARD"
);
-- EX_MEMBER 값 기입
INSERT INTO EX_MEMBER VALUES ('KH0001', '0001', '김김김', '123123@naver.com')
;

-- EX_CASHCARD 값 기입
INSERT INTO EX_CASHCARD VALUES ('체크카드')
;
INSERT INTO EX_CASHCARD VALUES ('현금')
;
INSERT INTO EX_CASHCARD VALUES ('신용카드')
;

-- EX_CATEGORY 값 기입
INSERT INTO EX_CATEGORY VALUES ('교통/차량')
;
INSERT INTO EX_CATEGORY VALUES ('식비')
;
INSERT INTO EX_CATEGORY VALUES ('주거/통신비')
;
INSERT INTO EX_CATEGORY VALUES ('문화생활')
;
INSERT INTO EX_CATEGORY VALUES ('마트/편의점')
;
INSERT INTO EX_CATEGORY VALUES ('패션/미용')
;
INSERT INTO EX_CATEGORY VALUES ('생활용품')
;
INSERT INTO EX_CATEGORY VALUES ('건강')
;
INSERT INTO EX_CATEGORY VALUES ('교육')
;
INSERT INTO EX_CATEGORY VALUES ('경조사/회비')
;


INSERT INTO EX VALUES (TO_DATE('20230727', 'YYYY-MM-DD'), SEQ_EX.NEXTVAL, 'KH0001', '2900', '교통/차량', '체크카드', '버스비', NULL)
;
INSERT INTO EX VALUES (TO_DATE('20230727', 'YYYY-MM-DD'), SEQ_EX.NEXTVAL, 'KH0001', '5100', '마트/편의점', '체크카드', '아보카도바나나쥬스', NULL)
;


